version: '2.1'

services:
  sifitest:
    image: dcdocker1.simpli.fi:5000/simplifi-test:20171012144628
    ports:
      - 5433:5432
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.11.0.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_CREATE_TOPICS: "sales_events:4:1,log_events:8:1"
  neo4j:
    image: neo4j:3.3.3
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687
